// Generated by CoffeeScript 2.5.1
var tree_data;

tree_data = {
  name: 'root',
  children: [
    {
      name: 'foo',
      children: [
        {
          children: []
        },
        {
          children: [
            {
              children: []
            },
            {
              children: []
            },
            {
              children: []
            }
          ]
        },
        {
          children: []
        },
        {
          name: 'bar',
          children: [
            {
              children: []
            },
            {
              children: []
            },
            {
              children: []
            },
            {
              name: 'ouch',
              children: []
            },
            {
              children: []
            }
          ]
        }
      ]
    },
    {
      children: [
        {
          children: [
            {
              children: []
            },
            {
              children: [
                {
                  children: []
                },
                {
                  children: []
                },
                {
                  children: []
                }
              ]
            }
          ]
        }
      ]
    },
    {
      children: [
        {
          children: []
        },
        {
          children: []
        }
      ]
    }
  ]
};
