// Generated by CoffeeScript 2.5.1
var create_layer_node, getCurrentCanvas, ref, resizeHandler, resizeTimer, userAgent, view, vm;

getCurrentCanvas = function() {
  return {
    w: window.innerWidth,
    h: window.innerHeight,
    offset_y: 40
  };
};

resizeTimer = false;

resizeHandler = function() {
  if (resizeTimer !== false) {
    clearTimeout(resizeTimer);
  }
  return resizeTimer = setTimeout(function() {
    vm.create();
    return m.redraw();
  }, 500);
};

if (((ref = window.navigator) != null ? ref.userAgent : void 0) != null) {
  userAgent = window.navigator.userAgent;
  if (userAgent.indexOf('iPhone') >= 0 || userAgent.indexOf('iPad') >= 0 || userAgent.indexOf('android') >= 0) {
    window.addEventListener('orientationchange', resizeHandler);
  } else {
    window.addEventListener('resize', resizeHandler);
  }
}

create_layer_node = function(node, node_list, diag_list) {
  var len;
  len = node_list.length;
  node_list.push(textbox(node, len));
  if (node.children != null) {
    return node.children.map(function(child, i) {
      diag_list.push(diag_v(node, child));
      return create_layer_node(child, node_list, diag_list);
    });
  }
};

vm = {
  create: function() {
    var calculated_tree, canvas, compute_list, diag_list, fit_size, h, node_list, off_y, w;
    canvas = getCurrentCanvas();
    w = canvas.w;
    h = canvas.h;
    off_y = canvas.offset_y;
    calculated_tree = new TreeLayout(tree_data);
    fit_size = calculated_tree.size(w, h, off_y);
    node_list = [];
    diag_list = [];
    create_layer_node(fit_size, node_list, diag_list);
    compute_list = [text_svg(20, 30, 'Reingold Tilford Tree Layout', 'font-size: 3em;', null), ...node_list, ...diag_list];
    return frame(compute_list, w, h);
  }
};

view = {
  view: function(ctrl, args) {
    return vm.create();
  }
};

m.mount(document.getElementById('contents'), view);
