// Generated by CoffeeScript 2.5.1
var diag_v, frame, rect, text_svg, textbox;

frame = function(children, width, height, style = "background-color: cornflowerblue") {
  return m('svg', {
    x: 0,
    y: 0,
    width: width,
    height: height,
    style: style
  }, children);
};

rect = function(x, y, stroke = 'white', width = 50, height = 20) {
  var x_top, y_top;
  x_top = x - width / 2;
  y_top = y - height / 2;
  return m('rect', {
    rx: 5,
    x: x_top,
    y: y_top,
    width: width,
    height: height,
    stroke: stroke,
    fill: 'darkslategray',
    'stroke-width': 2
  });
};

text_svg = function(x, y, text, style = "font-size: 1em;", anchor = 'middle') {
  return m('text', {
    x: x,
    y: y,
    'text-anchor': anchor,
    'dominant-baseline': 'central',
    fill: 'white',
    style: style
  }, text);
};

textbox = function(x, y, text, stroke = 'white', width = 50, height = 20) {
  return [rect(x, y, stroke, width, height), text_svg(x, y, text)];
};

diag_v = function(start_x, start_y, end_x, end_y, target_height = 20) {
  var first, move_to_start, second, third;
  if (start_y < end_y) {
    start_y = start_y + target_height / 2;
    end_y = end_y - target_height / 2;
  } else {
    start_y = start_y - target_height / 2;
    end_y = end_y + target_height / 2;
  }
  move_to_start = `M${start_x},${start_y}`;
  first = `C${start_x},${(end_y - start_y) / 2 + start_y}`;
  second = `${end_x},${(end_y - start_y) / 2 + start_y}`;
  third = `${end_x},${end_y}`;
  return m('path', {
    d: `${move_to_start} ${first} ${second} ${third}`,
    stroke: 'yellowgreen',
    fill: 'transparent',
    'stroke-width': 1.5
  });
};
